### ISSUE TITLE
Обработать исключение для веба

### ISSUE THREAD

**Issue by vsalex** [AndreyAD1/wind-speed-calculation#16]
При пустом идентификаторе метеостанции вылетает вот такая ошибка:

```
raise RP5FormatError
exceptions.RP5FormatError
```

**Comment by maylunova** [comment]
случай отправки формы с пустыми ID и периодом исключен атрибутами required, которые отвечают за обязательность заполнения.

**Comment by maylunova** [comment]
Reopen issue:
обработать исключение для случая отправки несуществующего ID

**Comment by maylunova** [comment]
Oбработано исключение для случая отправки несуществующего ID: сделала новый html-шаблон, который возвращается, если словим RP5FormatError
