### ISSUE TITLE
Пояснения на странице рассчетов

### ISSUE THREAD

**Issue by vsalex** [AndreyAD1/wind-speed-calculation#19]
Хорошо бы на странице с графиком написать текстом по какой метеостанции и за какой период проводится расчет. Плюс написать заголовок для графиков и таблице.

**Comment by maylunova** [comment]
Добавлен текст в формате:
Расчет составлен для метостанции с  WMO ID {{ station_id }} за период с {{ start_date}} по {{ end_date }}.
