### ISSUE TITLE
Реализовать логику расчета 16 скоростей ветра по 16 направлениям ветра

### ISSUE THREAD

**Issue by vsalex** [AndreyAD1/wind-speed-calculation#6]

**Comment by vsalex** [comment]
@AndreyAD1 Это твоя часть :).

**Comment by AndreyAD1** [comment]
Это должен быт отдельный файл *.py и он должен:
1. загружать файл *.csv с данными наблюдений;
2. оставлять в файле только скорость и направление ветра;
3. вычислять повторяемость каждого сочетания скорости и направления ветра;
4. вычислять повторяемость каждой скорости ветра по каждому направлению ветра;
5. вычислять продолжительность каждой скорости ветра по каждому направлению ветра;
6. строить функцию v=f(F)
6. для каждого румба вычислять значение режимной функции ветра F;
7. вычислять скорость ветра по функции v=f(F).
